---
name: Dump

on:
  push:
    branches:
      - main

jobs:
  setenv:
    runs-on: ubuntu-latest

    steps:
      - name: dumpit
        run: |
          echo "HERE=${{ github.event.repository.isfork }}"
          echo ${{ github.event.pull_request.head.repo.full_name }} ${{ github.repository }}
