---
name: Dump

on:
  push:
    branches:
      - main

jobs:
  setenv:
    runs-on: ubuntu-latest

    steps:
      - name: dumpit
        run: |
          echo "HERE=${{ github.repository.is_not_forked }}"
          echo "HERE2=${{ github.event.pull_request.head.repo.full_name }}"
          echo "HERE3=${{ github.repository }}"
