---
name: Dump

on:
  push:
    branches:
      - main

jobs:
  setenv:
    runs-on: ubuntu-latest

    steps:
      - name: dumpit
        run: |
          echo "${{ github.event.repository.fork }}"
          echo "###"
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
